name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set build tag as env var
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/certstream-server-go:latest --tag $DOCKERHUB_USERNAME/certstream-server-go:v${{ env.TAG }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/certstream-server-go
